---
- name: install packages
  package:
    name: "{{ centos_installer_packages }}"
    state: "{{ centos_installer_package_state }}"

- name: create temporary target directory
  tempfile:
    state: directory
    prefix: iso
  register: tmpdir_dest

- name: create centos image target directory
  file:
    state: directory
    path: "{{ centos_installer_target_dir }}"

- name: fetch centos source iso
  get_url:
    url: "{{ centos_installer_image | default(centos_installer_image_url) }}"
    dest: "{{ centos_installer_iso_path }}"

- name: create temporary mount fstab
  tempfile:
    state: directory
    prefix: fstab
  register: mntfile_dest

- name: create temporary mount directory
  tempfile:
    state: directory
    prefix: mnt
  register: mntdir_dest

- name: mount centos source iso
  mount:
    src: "{{ centos_installer_iso_path }}"
    path: "{{ mntdir_dest.path }}"
    state: mounted
    opts: loop
    fstype: iso9660

- name: extract source iso files
  command: "cp -a {{ mntdir_dest.path }}/. {{ tmpdir_dest.path }}/"
  args:
    warn: no
  tags:
    - skip_ansible_lint

- name: unmount centos source iso
  mount:
    src: "{{ centos_installer_iso_path }}"
    path: "{{ mntdir_dest.path }}"
    state: absent
    opts: loop

- name: remove centos source iso
  file:
    path: "{{ centos_installer_iso_path }}"
    state: absent

- name: remove temporary mount directory
  file:
    path: "{{ mntdir_dest.path }}"
    state: absent

- name: remove temporary mount fstab
  file:
    path: "{{ mntfile_dest.path }}"
    state: absent

- name: check isolinux configuration file location
  command: "find {{ tmpdir_dest.path }} -maxdepth 2 -name isolinux.cfg"
  register: isolinux_cfgdest
  changed_when: false

- name: configure isolinux
  lineinfile:
    path: "{{ isolinux_cfgdest.stdout }}"
    regexp: 'timeout\s+[0-9]+'
    line: 'timeout 1'

- name: register kickstart file location
  set_fact:
    ks_file: "ks.cfg"

- name: create kickstart file
  template:
    src: "{{ centos_installer_ks_template }}"
    dest: "{{ tmpdir_dest.path }}/{{ ks_file }}"
  vars:
    _hostname: "{{ centos_installer_hostname }}"
    _timezone: "{{ centos_installer_timezone }}"
    _root_password: "{{ centos_installer_root_password }}"
    _username: "{{ centos_installer_username }}"
    _password: "{{ centos_installer_password }}"
    _homedir: "{{ centos_installer_userhome }}"
    _sshkey: "{{ [centos_installer_sshkey] | flatten }}"
    _interface: "{{ centos_installer_interface }}"
    _halt: "{{ centos_installer_halt | default('false') }}"
    _keyboard: "{{ centos_installer_ks_keyboard }}"
    _disk: "{{ centos_installer_disk }}"
    _baseurl: "{{ centos_installer_baseurl }}"
    _partitioning: "{{ centos_installer_ks_partitioning }}"
    _kickstart_extra: "{{ centos_installer_ks_extra }}"
    _clearpart: "{{ centos_installer_clearpart }}"

- name: validate kickstart RHEL7 syntax
  command: "ksvalidator {{ tmpdir_dest.path }}/{{ ks_file }} -v RHEL7"
  when: centos_installer_ks_template == 'centos7'

- name: validate kickstart RHEL8 syntax
  command: "ksvalidator {{ tmpdir_dest.path }}/{{ ks_file }} -v RHEL8"
  when: centos_installer_ks_template in ['centos8', 'stream8']

- name: check isolinux boot file location
  command: "find {{ tmpdir_dest.path }} -maxdepth 2 -name isolinux.cfg"
  register: isolinux_bootdest
  changed_when: false

- name: set bootloader kickstart configuration
  template:
    src: isolinux.cfg.j2
    dest: "{{ isolinux_bootdest.stdout }}"
  vars:
    ks_url: "cdrom:/{{ ks_file }}"
    volume: "{{ centos_installer_iso_volume }}"

- name: check isolinux bin file location
  command: "find {{ tmpdir_dest.path }} -maxdepth 2 -name isolinux.bin"
  register: isolinux_bindest
  changed_when: false

- name: check isolinux boot cat file location
  command: "find {{ tmpdir_dest.path }} -maxdepth 2 -name boot.cat"
  register: isolinux_bootcatdest
  changed_when: false

- name: compute isolinux bin
  set_fact:
    isolinux_bin: "{{ isolinux_bindest.stdout | regex_replace(tmpdir_dest.path + '/', '') }}"
    isolinux_cat: "{{ isolinux_bootcatdest.stdout | regex_replace(tmpdir_dest.path + '/', '') }}"

- name: create centos autoinstall iso
  command: "{{ mkisofs_cmd }} -V '{{ centos_installer_iso_volume }}' -b {{ isolinux_bin }} -c {{ isolinux_cat }} -o {{ mkisofs_out }} ."
  args:
    chdir: "{{ tmpdir_dest.path }}"
  vars:
    mkisofs_cmd: "mkisofs -J -R -v -T -no-emul-boot -boot-load-size 4 -boot-info-table"
    mkisofs_out: "{{ centos_installer_target_dir }}/{{ centos_installer_target_filename }}"
  changed_when: false

- name: make iso bootable
  command: "isohybrid {{ centos_installer_target_dir }}/{{ centos_installer_target_filename }}"
  changed_when: false

- name: implant iso md5sum
  command: "implantisomd5 {{ centos_installer_target_dir }}/{{ centos_installer_target_filename }}"
  changed_when: false

- name: remove temporary directories
  file:
    path: "{{ tmpdir_dest.path }}"
    state: absent
