---
- name: prepare cache

  hosts: localhost

  connection: local

  gather_facts: no

  vars_files:
    - vars.yml

  tasks:

    - block:

        - name: install kvm requirements
          apt:
            name:
              - qemu
              - qemu-kvm
              - qemu-efi
              - libvirt-clients
              - libvirt-daemon-system
              - libvirt-daemon-system-systemd
              - python3-libvirt

        - name: create molecule cache dir
          file:
            path: "{{ cache_dir }}"
            state: directory
            owner: libvirt-qemu
            group: kvm
            mode: 0755

      become: yes

    - name: test for presence of kvm key pair
      stat:
        path: "{{ kvm_key_pair_path }}"
      register: kvm_key_pair_local

    - name: create kvm key pair
      command: "ssh-keygen -t rsa -f {{ kvm_key_pair_path }} -q -P '' -C ''"
      when: not kvm_key_pair_local.stat.exists
