---
- name: prepare cache

  hosts: localhost

  connection: local

  gather_facts: no

  vars_files:
    - vars.yml

  tasks:

    - name: create molecule cache dir
      file:
        path: "{{ cache_dir }}"
        state: directory
        mode: 0777

    - name: test for presence of kvm key pair
      stat:
        path: "{{ kvm_key_pair_path }}"
      register: kvm_key_pair_local

    - name: create kvm key pair
      command: "ssh-keygen -t rsa -f {{ kvm_key_pair_path }} -q -P '' -C ''"
      when: not kvm_key_pair_local.stat.exists
