---
- import_playbook: inventory.yml


- name: decommission instances

  hosts: molecule

  gather_facts: false

  no_log: "{{ molecule_no_log }}"

  tasks:

    - name: destroy instances
      community.aws.ec2_instance:
        region: "{{ aws_env_region }}"
        state: absent
        instance_ids:
          - "{{ instance_id }}"
      delegate_to: localhost
