---
bridge_net: '192.168.255.0/24'
__bridge_net: "{{ bridge_net | ipv4('network/prefix') }}"
bridge_host: "{{ __bridge_net | nthhost(1) }}"
bridge_prefix: "{{ __bridge_net | ipaddr('prefix') }}"
bridge_name: dummybr0
iface_name: dummy0
ssh_keypair: "{{ playbook_dir }}/id_rsa"
centos_installers:
  centos7:
    dest: file://{{ playbook_dir }}/centos7.iso
    url: http://mirror.rackspace.com/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso
  stream8:
    dest: file://{{ playbook_dir }}/stream8.iso
    url: http://mirror.rackspace.com/CentOS/8-stream/isos/x86_64/CentOS-Stream-8-x86_64-20210204-boot.iso
  alma8:
    dest: file://{{ playbook_dir }}/alma8.iso
    url: https://repo.almalinux.org/almalinux/8.3-beta/isos/x86_64/AlmaLinux-8.3-beta-1-x86_64-minimal.iso
vms:
  - centos_installer_hostname: centos7-lvm
    centos_installer_ref: centos7
    centos_installer_interface:
      static: true
      ipaddress: "{{ __bridge_net | nthhost(2) }}"
      network: "{{ __bridge_net | ipaddr('network') }}"
      netmask: "{{ __bridge_net | ipaddr('netmask') }}"
      gateway: "{{ bridge_host }}"
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
    centos_partitioning_method: lvm
    centos_ks_partitioning: autopart
  - centos_installer_hostname: centos7-gpt
    centos_installer_ref: centos7
    centos_installer_interface:
      static: true
      ipaddress: "{{ __bridge_net | nthhost(3) }}"
      network: "{{ __bridge_net | ipaddr('network') }}"
      netmask: "{{ __bridge_net | ipaddr('netmask') }}"
      gateway: "{{ bridge_host }}"
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
    centos_partitioning_method: regular
    centos_ks_partitioning: |
      clearpart --all --initlabel
      part swap --size=4000
      part /boot --fstype=xfs --size=500
      part / --fstype=xfs --grow --size=1
