---
- import_playbook: inventory.yml


- name: verify iso creation

  hosts: molecule

  gather_facts: false

  vars_files:
    - ./vars.yml

  tasks:

    - name: retrieve iso status
      stat:
        path: "{{ cache_dir }}/{{ vm.centos_installer_hostname }}.iso"
      vars:
        centos_installer_target_dir: "{{ playbook_dir }}"
      loop_control:
        loop_var: vm
        label: "{{ vm.centos_installer_hostname }}"
      loop: "{{ vms }}"
      register: vm_isos

    - name: verify iso creation
      fail:
        msg: unable to find iso
      loop_control:
        loop_var: vm_iso
        label: "{{ vm_iso.stat.path | default('unknown') }}"
      loop: "{{ vm_isos.results }}"
      when: not (vm_iso.stat.exists | bool)


- name: add guests to inventory

  hosts: molecule

  become: yes

  vars_files:
    - ./vars.yml

  tasks:

    - name: add debug ssh key
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ debug_pubkey }}"

    - name: add guest to inventory
      add_host:
        name: "{{ guest_hostname }}"
        groups:
          - install
        ansible_user: molecule
        ansible_host: "{{ guest_address }}"
        ansible_port: "{{ guest_port }}"
        ansible_ssh_private_key_file: "{{ kvm_key_pair_path }}"
        partition_method: "{{ guest.centos_partitioning_method }}"
        disk_size: "{{ guest.centos_installer_disk_size }}"
      vars:
        guest_hostname: "{{ guest.centos_installer_hostname }}"
        bridge_address: "{{ guest.centos_installer_interface.ipaddress }}"
        snat_address: "{{ ansible_host }}"
        guest_address: "{{ (aws_provision | default('no') | bool) | ternary(snat_address, bridge_address) }}"
        bridge_port: 22
        snat_port: "{{ (ssh_port_base | int) + (port_offset | int) }}"
        guest_port: "{{ (aws_provision | default('no') | bool) | ternary(snat_port, bridge_port) }}"
      loop_control:
        loop_var: guest
        index_var: port_offset
        label: "{{ guest.centos_installer_hostname }}"
      loop: "{{ vms }}"


- name: verify guests

  hosts: install

  gather_facts: no

  vars_files:
    - ./vars.yml

  tasks:

    - name: debug connection parameters
      debug:
        msg: "ssh {{ ansible_user }}@{{ ansible_host }} {{ ansible_ssh_common_args | default('') }} -i {{ ansible_ssh_private_key_file }} -p {{ ansible_port }}"

    - name: test connection
      wait_for_connection:
        sleep: 10
        timeout: 1200

    - name: gather facts
      setup:

    - name: gather partition info
      shell: "lsblk -l | grep /$"
      register: lsblk_output

    - name: check static partitioning
      fail:
        msg: "expected plain partitioning, found '{{ lsblk_output.stdout }}'"
      when:
        - partition_method == 'regular'
        - lsblk_output.stdout is not search("part") or
          lsblk_output.stdout is search("lvm")

    - block:

        - name: check lvm partitioning
          fail:
            msg: "lvm partitioning failed: {{ lsblk_output.stdout }}"
          when:
            - lsblk_output.stdout is not search('lvm')

      when: partition_method == 'lvm'

    - name: debug disk size
      debug:
        msg: "{{ installer_root_device }}"
      vars:
        installer_root_device: "{{ ansible_mounts | selectattr('mount', 'equalto', '/') | list | first }}"

    - name: check root device size
      fail:
        msg: "{{ installer_root_size }} < {{ installer_root_threshold }} ({{ disk_size }})"
      vars:
        installer_root_device: "{{ ansible_mounts | selectattr('mount', 'equalto', '/') | list | first }}"
        installer_root_size: "{{ installer_root_device.size_total }}"
        installer_root_threshold: "{{ (0.5 * (disk_size | int)) | int }}"
      when: (installer_root_size | int) < (installer_root_threshold | int)
