---
- name: Converge
  hosts: all
  vars:
    centos_installer_username: test
    centos_installer_password: "{{ 'test' | password_hash('sha512') }}"
  pre_tasks:
    - name: update apt package cache
      apt:
        update_cache: yes
      when: (ansible_os_family | lower) == 'debian'
  roles:
    - role: nephelaiio.centos-installer
