---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      host_key_checking: false
  playbooks:
    converge: ../converge.yml
    verify: ../verify.yml
    prepare: ../prepare.yml
    cleanup: ../cleanup.yml
  inventory:
    group_vars:
      all:
        kvm_enabled: true
        test_local: yes
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
