---
- name: Prepare

  hosts: all

  become: yes

  vars_files:
    - ../vars.yml

  tasks:

    - name: install python3
      apt:
        name: python3

    - name: install network manager
      apt:
        name: network-manager

    - name: create dummy bridge
      command: "nmcli con add ifname {{ bridge_name }} type bridge con-name {{ bridge_name }}"
      failed_when: false

    - name: create dummy interface
      command: "nmcli con add ifname {{ iface_name }} type dummy con-name {{ iface_name }}"
      failed_when: false

    - name: create dummy bridge slave
      command: "nmcli con add type bridge-slave ifname {{ iface_name }} master {{ bridge_name }} con-name {{ bridge_name }}-{{ iface_name }}"
      failed_when: false

    - name: set bridge interface ip address
      command: "nmcli con mod {{ bridge_name }} ipv4.addresses {{ bridge_host }}/{{ bridge_prefix }}"
      failed_when: false

    - name: set bridge interface ip method
      command: "nmcli con mod {{ bridge_name }} ipv4.method manual"

    - name: stop bridge interface
      command: "nmcli con down {{ bridge_name }}"
      failed_when: false

    - name: start bridge interface
      command: "nmcli con up {{ bridge_name }}"
      failed_when: false

    - name: masquerade bridge
      iptables:
        table: nat
        chain: POSTROUTING
        out_interface: "{{ ansible_default_ipv4.interface }}"
        source: "{{ bridge_net }}"
        destination: 0.0.0.0/0
        jump: MASQUERADE
        protocol: all
        state: present

    - name: enable ipv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: True

    - name: install kvm requirements
      apt:
        name:
          - qemu
          - qemu-kvm
          - qemu-efi
          - libvirt-clients
          - libvirt-daemon-system
          - libvirt-daemon-system-systemd
          - python3-libvirt
