---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: instance
    image: ami-03d315ad33b9d49c4
    instance_type: c5d.metal
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      host_key_checking: false
  playbooks:
    converge: ../converge.yml
    verify: ../verify.yml
    prepare: ../prepare.yml
    cleanup: ../cleanup.yml
    create: ../create.yml
    destroy: ../destroy.yml
  inventory:
    group_vars:
      all:
        kvm_enabled: true
        aws_region: us-east-1
        aws_subnet_id: subnet-d2a31c8b
verifier:
  name: ansible
scenario:
  converge_sequence:
    - converge
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
