---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
provisioner:
  name: ansible
  playbooks:
    converge: ../converge.yml
    verify: ../verify.yml
  inventory:
    group_vars:
      all:
        kvm_enabled: ${MOLECULE_TEST_KVM:-false}
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
